server:
  port: 8501

spring:
  application:
    name: gatewayForApp
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: ForUser     #路由标识，id唯一
          uri: lb://ClientUser    # 路由的目标地址
          predicates:
            - Path=/User/**
      #          filters:
      #            - AddRequestHeader=key,value


      #    filters为路由过滤器  default-filters为全局过滤器  优先级按照声明顺序递增
      #    order值一样时，先执行default-filters，在执行路由过滤器，在执行，GlobalFilter

      globalcors:   #全局跨域处理
        add-to-simple-url-handler-mapping: true     #不拦截CORS的询问请求
        corsConfigurations:
          '[/**]':
            allowedOrigins: #允许哪些网站的跨域请求
              - "http://localhost:8080"
            allowedMethods: # 允许跨域的ajax请求方式
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true  #是否允许携带cookie
            maxAge: 360000    # 这次跨域检测的有效期

  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password:  guest
    listener:
      simple:
        prefetch: 1   #每次只能获取一条消息，处理完才能获取下一条（提升消息处理速度，避免消息堆积）

