// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.example.user.proto;

import java.util.Calendar;
import java.util.List;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface userListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User.userListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     *字段： 类型  名称  =  索引值（id
     *每个字段都要定义唯一索引值
     *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
     *repeated代表集合（数组）的关键字
     * </pre>
     *
     * <code>repeated .User.userResponse userList = 1;</code>
     */
    java.util.List<UserProto.userResponse>
        getUserListList();
    /**
     * <pre>
     **
     *字段： 类型  名称  =  索引值（id
     *每个字段都要定义唯一索引值
     *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
     *repeated代表集合（数组）的关键字
     * </pre>
     *
     * <code>repeated .User.userResponse userList = 1;</code>
     */
    UserProto.userResponse getUserList(int index);
    /**
     * <pre>
     **
     *字段： 类型  名称  =  索引值（id
     *每个字段都要定义唯一索引值
     *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
     *repeated代表集合（数组）的关键字
     * </pre>
     *
     * <code>repeated .User.userResponse userList = 1;</code>
     */
    int getUserListCount();
    /**
     * <pre>
     **
     *字段： 类型  名称  =  索引值（id
     *每个字段都要定义唯一索引值
     *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
     *repeated代表集合（数组）的关键字
     * </pre>
     *
     * <code>repeated .User.userResponse userList = 1;</code>
     */
    java.util.List<? extends UserProto.userResponseOrBuilder>
        getUserListOrBuilderList();
    /**
     * <pre>
     **
     *字段： 类型  名称  =  索引值（id
     *每个字段都要定义唯一索引值
     *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
     *repeated代表集合（数组）的关键字
     * </pre>
     *
     * <code>repeated .User.userResponse userList = 1;</code>
     */
    UserProto.userResponseOrBuilder getUserListOrBuilder(
        int index);
  }
  /**
   * <pre>
   **
   *消息是gRPC描述信息的基本单位，类似Java的实体类
   *消息的名字对应生成代码后的类名
   *每个消息对应一个类
   * </pre>
   *
   * Protobuf type {@code User.userListResponse}
   */
  public static final class userListResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User.userListResponse)
      userListResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use userListResponse.newBuilder() to construct.
    private userListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private userListResponse() {
      userList_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new userListResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private userListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                userList_ = new java.util.ArrayList<UserProto.userResponse>();
                mutable_bitField0_ |= 0x00000001;
              }
              userList_.add(
                  input.readMessage(UserProto.userResponse.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          userList_ = java.util.Collections.unmodifiableList(userList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserProto.internal_static_User_userListResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserProto.internal_static_User_userListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserProto.userListResponse.class, UserProto.userListResponse.Builder.class);
    }

    public static final int USERLIST_FIELD_NUMBER = 1;
    private java.util.List<UserProto.userResponse> userList_;
    /**
     * <pre>
     **
     *字段： 类型  名称  =  索引值（id
     *每个字段都要定义唯一索引值
     *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
     *repeated代表集合（数组）的关键字
     * </pre>
     *
     * <code>repeated .User.userResponse userList = 1;</code>
     */
    @Override
    public java.util.List<UserProto.userResponse> getUserListList() {
      return userList_;
    }
    /**
     * <pre>
     **
     *字段： 类型  名称  =  索引值（id
     *每个字段都要定义唯一索引值
     *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
     *repeated代表集合（数组）的关键字
     * </pre>
     *
     * <code>repeated .User.userResponse userList = 1;</code>
     */
    @Override
    public java.util.List<? extends UserProto.userResponseOrBuilder>
        getUserListOrBuilderList() {
      return userList_;
    }
    /**
     * <pre>
     **
     *字段： 类型  名称  =  索引值（id
     *每个字段都要定义唯一索引值
     *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
     *repeated代表集合（数组）的关键字
     * </pre>
     *
     * <code>repeated .User.userResponse userList = 1;</code>
     */
    @Override
    public int getUserListCount() {
      return userList_.size();
    }
    /**
     * <pre>
     **
     *字段： 类型  名称  =  索引值（id
     *每个字段都要定义唯一索引值
     *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
     *repeated代表集合（数组）的关键字
     * </pre>
     *
     * <code>repeated .User.userResponse userList = 1;</code>
     */
    @Override
    public UserProto.userResponse getUserList(int index) {
      return userList_.get(index);
    }
    /**
     * <pre>
     **
     *字段： 类型  名称  =  索引值（id
     *每个字段都要定义唯一索引值
     *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
     *repeated代表集合（数组）的关键字
     * </pre>
     *
     * <code>repeated .User.userResponse userList = 1;</code>
     */
    @Override
    public UserProto.userResponseOrBuilder getUserListOrBuilder(
        int index) {
      return userList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < userList_.size(); i++) {
        output.writeMessage(1, userList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < userList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserProto.userListResponse)) {
        return super.equals(obj);
      }
      UserProto.userListResponse other = (UserProto.userListResponse) obj;

      if (!getUserListList()
          .equals(other.getUserListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUserListCount() > 0) {
        hash = (37 * hash) + USERLIST_FIELD_NUMBER;
        hash = (53 * hash) + getUserListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserProto.userListResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserProto.userListResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserProto.userListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserProto.userListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserProto.userListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserProto.userListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserProto.userListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserProto.userListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserProto.userListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserProto.userListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserProto.userListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserProto.userListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserProto.userListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *消息是gRPC描述信息的基本单位，类似Java的实体类
     *消息的名字对应生成代码后的类名
     *每个消息对应一个类
     * </pre>
     *
     * Protobuf type {@code User.userListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User.userListResponse)
        UserProto.userListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserProto.internal_static_User_userListResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserProto.internal_static_User_userListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserProto.userListResponse.class, UserProto.userListResponse.Builder.class);
      }

      // Construct using org.example.proto.user.UserProto.userListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserListFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (userListBuilder_ == null) {
          userList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          userListBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserProto.internal_static_User_userListResponse_descriptor;
      }

      @Override
      public UserProto.userListResponse getDefaultInstanceForType() {
        return UserProto.userListResponse.getDefaultInstance();
      }

      @Override
      public UserProto.userListResponse build() {
        UserProto.userListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserProto.userListResponse buildPartial() {
        UserProto.userListResponse result = new UserProto.userListResponse(this);
        int from_bitField0_ = bitField0_;
        if (userListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            userList_ = java.util.Collections.unmodifiableList(userList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.userList_ = userList_;
        } else {
          result.userList_ = userListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserProto.userListResponse) {
          return mergeFrom((UserProto.userListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserProto.userListResponse other) {
        if (other == UserProto.userListResponse.getDefaultInstance()) return this;
        if (userListBuilder_ == null) {
          if (!other.userList_.isEmpty()) {
            if (userList_.isEmpty()) {
              userList_ = other.userList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUserListIsMutable();
              userList_.addAll(other.userList_);
            }
            onChanged();
          }
        } else {
          if (!other.userList_.isEmpty()) {
            if (userListBuilder_.isEmpty()) {
              userListBuilder_.dispose();
              userListBuilder_ = null;
              userList_ = other.userList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              userListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserListFieldBuilder() : null;
            } else {
              userListBuilder_.addAllMessages(other.userList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserProto.userListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserProto.userListResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<UserProto.userResponse> userList_ =
        java.util.Collections.emptyList();
      private void ensureUserListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          userList_ = new java.util.ArrayList<UserProto.userResponse>(userList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          UserProto.userResponse, UserProto.userResponse.Builder, UserProto.userResponseOrBuilder> userListBuilder_;

      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public java.util.List<UserProto.userResponse> getUserListList() {
        if (userListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(userList_);
        } else {
          return userListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public int getUserListCount() {
        if (userListBuilder_ == null) {
          return userList_.size();
        } else {
          return userListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public UserProto.userResponse getUserList(int index) {
        if (userListBuilder_ == null) {
          return userList_.get(index);
        } else {
          return userListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public Builder setUserList(
          int index, UserProto.userResponse value) {
        if (userListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserListIsMutable();
          userList_.set(index, value);
          onChanged();
        } else {
          userListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public Builder setUserList(
          int index, UserProto.userResponse.Builder builderForValue) {
        if (userListBuilder_ == null) {
          ensureUserListIsMutable();
          userList_.set(index, builderForValue.build());
          onChanged();
        } else {
          userListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public Builder addUserList(UserProto.userResponse value) {
        if (userListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserListIsMutable();
          userList_.add(value);
          onChanged();
        } else {
          userListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public Builder addUserList(
          int index, UserProto.userResponse value) {
        if (userListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserListIsMutable();
          userList_.add(index, value);
          onChanged();
        } else {
          userListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public Builder addUserList(
          UserProto.userResponse.Builder builderForValue) {
        if (userListBuilder_ == null) {
          ensureUserListIsMutable();
          userList_.add(builderForValue.build());
          onChanged();
        } else {
          userListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public Builder addUserList(
          int index, UserProto.userResponse.Builder builderForValue) {
        if (userListBuilder_ == null) {
          ensureUserListIsMutable();
          userList_.add(index, builderForValue.build());
          onChanged();
        } else {
          userListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public Builder addAllUserList(
          Iterable<? extends UserProto.userResponse> values) {
        if (userListBuilder_ == null) {
          ensureUserListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, userList_);
          onChanged();
        } else {
          userListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public Builder clearUserList() {
        if (userListBuilder_ == null) {
          userList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          userListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public Builder removeUserList(int index) {
        if (userListBuilder_ == null) {
          ensureUserListIsMutable();
          userList_.remove(index);
          onChanged();
        } else {
          userListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public UserProto.userResponse.Builder getUserListBuilder(
          int index) {
        return getUserListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public UserProto.userResponseOrBuilder getUserListOrBuilder(
          int index) {
        if (userListBuilder_ == null) {
          return userList_.get(index);  } else {
          return userListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public java.util.List<? extends UserProto.userResponseOrBuilder>
           getUserListOrBuilderList() {
        if (userListBuilder_ != null) {
          return userListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(userList_);
        }
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public UserProto.userResponse.Builder addUserListBuilder() {
        return getUserListFieldBuilder().addBuilder(
            UserProto.userResponse.getDefaultInstance());
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public UserProto.userResponse.Builder addUserListBuilder(
          int index) {
        return getUserListFieldBuilder().addBuilder(
            index, UserProto.userResponse.getDefaultInstance());
      }
      /**
       * <pre>
       **
       *字段： 类型  名称  =  索引值（id
       *每个字段都要定义唯一索引值
       *不可使用19000-19999之间的标识号，protobuf协议对其进行了预留
       *repeated代表集合（数组）的关键字
       * </pre>
       *
       * <code>repeated .User.userResponse userList = 1;</code>
       */
      public java.util.List<UserProto.userResponse.Builder>
           getUserListBuilderList() {
        return getUserListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          UserProto.userResponse, UserProto.userResponse.Builder, UserProto.userResponseOrBuilder>
          getUserListFieldBuilder() {
        if (userListBuilder_ == null) {
          userListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              UserProto.userResponse, UserProto.userResponse.Builder, UserProto.userResponseOrBuilder>(
                  userList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          userList_ = null;
        }
        return userListBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User.userListResponse)
    }

    // @@protoc_insertion_point(class_scope:User.userListResponse)
    private static final UserProto.userListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserProto.userListResponse();
    }

    public static UserProto.userListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<userListResponse>
        PARSER = new com.google.protobuf.AbstractParser<userListResponse>() {
      @Override
      public userListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new userListResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<userListResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<userListResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public UserProto.userListResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface userResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User.userResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string user_name = 10;</code>
     * @return The userName.
     */
    String getUserName();
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string user_name = 10;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <pre>
     *身份证号
     * </pre>
     *
     * <code>string user_id = 20;</code>
     * @return The userId.
     */
    String getUserId();
    /**
     * <pre>
     *身份证号
     * </pre>
     *
     * <code>string user_id = 20;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <pre>
     *所绑定的车辆信息
     * </pre>
     *
     * <code>repeated string Vehicle = 30;</code>
     * @return A list containing the vehicle.
     */
    java.util.List<String>
        getVehicleList();
    /**
     * <pre>
     *所绑定的车辆信息
     * </pre>
     *
     * <code>repeated string Vehicle = 30;</code>
     * @return The count of vehicle.
     */
    int getVehicleCount();
    /**
     * <pre>
     *所绑定的车辆信息
     * </pre>
     *
     * <code>repeated string Vehicle = 30;</code>
     * @param index The index of the element to return.
     * @return The vehicle at the given index.
     */
    String getVehicle(int index);
    /**
     * <pre>
     *所绑定的车辆信息
     * </pre>
     *
     * <code>repeated string Vehicle = 30;</code>
     * @param index The index of the value to return.
     * @return The bytes of the vehicle at the given index.
     */
    com.google.protobuf.ByteString
        getVehicleBytes(int index);
  }
  /**
   * Protobuf type {@code User.userResponse}
   */
  public static final class userResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User.userResponse)
      userResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use userResponse.newBuilder() to construct.
    private userResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private userResponse() {
      userName_ = "";
      userId_ = "";
      vehicle_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new userResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private userResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 82: {
              String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 162: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 242: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                vehicle_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              vehicle_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          vehicle_ = vehicle_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserProto.internal_static_User_userResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserProto.internal_static_User_userResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserProto.userResponse.class, UserProto.userResponse.Builder.class);
    }

    public static final int USER_NAME_FIELD_NUMBER = 10;
    private volatile Object userName_;
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string user_name = 10;</code>
     * @return The userName.
     */
    @Override
    public String getUserName() {
      Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string user_name = 10;</code>
     * @return The bytes for userName.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_FIELD_NUMBER = 20;
    private volatile Object userId_;
    /**
     * <pre>
     *身份证号
     * </pre>
     *
     * <code>string user_id = 20;</code>
     * @return The userId.
     */
    @Override
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *身份证号
     * </pre>
     *
     * <code>string user_id = 20;</code>
     * @return The bytes for userId.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VEHICLE_FIELD_NUMBER = 30;
    private com.google.protobuf.LazyStringList vehicle_;
    /**
     * <pre>
     *所绑定的车辆信息
     * </pre>
     *
     * <code>repeated string Vehicle = 30;</code>
     * @return A list containing the vehicle.
     */
    public com.google.protobuf.ProtocolStringList
        getVehicleList() {
      return vehicle_;
    }
    /**
     * <pre>
     *所绑定的车辆信息
     * </pre>
     *
     * <code>repeated string Vehicle = 30;</code>
     * @return The count of vehicle.
     */
    public int getVehicleCount() {
      return vehicle_.size();
    }
    /**
     * <pre>
     *所绑定的车辆信息
     * </pre>
     *
     * <code>repeated string Vehicle = 30;</code>
     * @param index The index of the element to return.
     * @return The vehicle at the given index.
     */
    public String getVehicle(int index) {
      return vehicle_.get(index);
    }
    /**
     * <pre>
     *所绑定的车辆信息
     * </pre>
     *
     * <code>repeated string Vehicle = 30;</code>
     * @param index The index of the value to return.
     * @return The bytes of the vehicle at the given index.
     */
    public com.google.protobuf.ByteString
        getVehicleBytes(int index) {
      return vehicle_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, userName_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 20, userId_);
      }
      for (int i = 0; i < vehicle_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 30, vehicle_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, userName_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, userId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < vehicle_.size(); i++) {
          dataSize += computeStringSizeNoTag(vehicle_.getRaw(i));
        }
        size += dataSize;
        size += 2 * getVehicleList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserProto.userResponse)) {
        return super.equals(obj);
      }
      UserProto.userResponse other = (UserProto.userResponse) obj;

      if (!getUserName()
          .equals(other.getUserName())) return false;
      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getVehicleList()
          .equals(other.getVehicleList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      if (getVehicleCount() > 0) {
        hash = (37 * hash) + VEHICLE_FIELD_NUMBER;
        hash = (53 * hash) + getVehicleList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserProto.userResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserProto.userResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserProto.userResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserProto.userResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserProto.userResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserProto.userResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserProto.userResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserProto.userResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserProto.userResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserProto.userResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserProto.userResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserProto.userResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserProto.userResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User.userResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User.userResponse)
        UserProto.userResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserProto.internal_static_User_userResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserProto.internal_static_User_userResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserProto.userResponse.class, UserProto.userResponse.Builder.class);
      }

      // Construct using org.example.proto.user.UserProto.userResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        userName_ = "";

        userId_ = "";

        vehicle_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserProto.internal_static_User_userResponse_descriptor;
      }

      @Override
      public UserProto.userResponse getDefaultInstanceForType() {
        return UserProto.userResponse.getDefaultInstance();
      }

      @Override
      public UserProto.userResponse build() {
        UserProto.userResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserProto.userResponse buildPartial() {
        UserProto.userResponse result = new UserProto.userResponse(this);
        int from_bitField0_ = bitField0_;
        result.userName_ = userName_;
        result.userId_ = userId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          vehicle_ = vehicle_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.vehicle_ = vehicle_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserProto.userResponse) {
          return mergeFrom((UserProto.userResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserProto.userResponse other) {
        if (other == UserProto.userResponse.getDefaultInstance()) return this;
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.vehicle_.isEmpty()) {
          if (vehicle_.isEmpty()) {
            vehicle_ = other.vehicle_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVehicleIsMutable();
            vehicle_.addAll(other.vehicle_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserProto.userResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserProto.userResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object userName_ = "";
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string user_name = 10;</code>
       * @return The userName.
       */
      public String getUserName() {
        Object ref = userName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string user_name = 10;</code>
       * @return The bytes for userName.
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string user_name = 10;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string user_name = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string user_name = 10;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private Object userId_ = "";
      /**
       * <pre>
       *身份证号
       * </pre>
       *
       * <code>string user_id = 20;</code>
       * @return The userId.
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *身份证号
       * </pre>
       *
       * <code>string user_id = 20;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *身份证号
       * </pre>
       *
       * <code>string user_id = 20;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *身份证号
       * </pre>
       *
       * <code>string user_id = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *身份证号
       * </pre>
       *
       * <code>string user_id = 20;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList vehicle_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureVehicleIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          vehicle_ = new com.google.protobuf.LazyStringArrayList(vehicle_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *所绑定的车辆信息
       * </pre>
       *
       * <code>repeated string Vehicle = 30;</code>
       * @return A list containing the vehicle.
       */
      public com.google.protobuf.ProtocolStringList
          getVehicleList() {
        return vehicle_.getUnmodifiableView();
      }
      /**
       * <pre>
       *所绑定的车辆信息
       * </pre>
       *
       * <code>repeated string Vehicle = 30;</code>
       * @return The count of vehicle.
       */
      public int getVehicleCount() {
        return vehicle_.size();
      }
      /**
       * <pre>
       *所绑定的车辆信息
       * </pre>
       *
       * <code>repeated string Vehicle = 30;</code>
       * @param index The index of the element to return.
       * @return The vehicle at the given index.
       */
      public String getVehicle(int index) {
        return vehicle_.get(index);
      }
      /**
       * <pre>
       *所绑定的车辆信息
       * </pre>
       *
       * <code>repeated string Vehicle = 30;</code>
       * @param index The index of the value to return.
       * @return The bytes of the vehicle at the given index.
       */
      public com.google.protobuf.ByteString
          getVehicleBytes(int index) {
        return vehicle_.getByteString(index);
      }
      /**
       * <pre>
       *所绑定的车辆信息
       * </pre>
       *
       * <code>repeated string Vehicle = 30;</code>
       * @param index The index to set the value at.
       * @param value The vehicle to set.
       * @return This builder for chaining.
       */
      public Builder setVehicle(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVehicleIsMutable();
        vehicle_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *所绑定的车辆信息
       * </pre>
       *
       * <code>repeated string Vehicle = 30;</code>
       * @param value The vehicle to add.
       * @return This builder for chaining.
       */
      public Builder addVehicle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVehicleIsMutable();
        vehicle_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *所绑定的车辆信息
       * </pre>
       *
       * <code>repeated string Vehicle = 30;</code>
       * @param values The vehicle to add.
       * @return This builder for chaining.
       */
      public Builder addAllVehicle(
          Iterable<String> values) {
        ensureVehicleIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vehicle_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *所绑定的车辆信息
       * </pre>
       *
       * <code>repeated string Vehicle = 30;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehicle() {
        vehicle_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *所绑定的车辆信息
       * </pre>
       *
       * <code>repeated string Vehicle = 30;</code>
       * @param value The bytes of the vehicle to add.
       * @return This builder for chaining.
       */
      public Builder addVehicleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureVehicleIsMutable();
        vehicle_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }




      // @@protoc_insertion_point(builder_scope:User.userResponse)
    }

    // @@protoc_insertion_point(class_scope:User.userResponse)
    private static final UserProto.userResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserProto.userResponse();
    }

    public static UserProto.userResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<userResponse>
        PARSER = new com.google.protobuf.AbstractParser<userResponse>() {
      @Override
      public userResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new userResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<userResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<userResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public UserProto.userResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_userListResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_userListResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_userResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_userResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nUser.proto\022\004User\032\033google/protobuf/empt" +
      "y.proto\"8\n\020userListResponse\022$\n\010userList\030" +
      "\001 \003(\0132\022.User.userResponse\"C\n\014userRespons" +
      "e\022\021\n\tuser_name\030\n \001(\t\022\017\n\007user_id\030\024 \001(\t\022\017\n" +
      "\007Vehicle\030\036 \003(\t2N\n\013UserService\022?\n\013getAllU" +
      "sers\022\026.google.protobuf.Empty\032\026.User.user" +
      "ListResponse\"\000B%\n\026org.example.proto.user" +
      "B\tUserProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_User_userListResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_userListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_userListResponse_descriptor,
        new String[] { "UserList", });
    internal_static_User_userResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_User_userResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_userResponse_descriptor,
        new String[] { "UserName", "UserId", "Vehicle", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
