server:
  port: 9000


spring:
  application:
    name: AdministratorService

  datasource:
    url: jdbc:mysql://localhost:3306/Smart_parking_data?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "001124"
    driver-class-name: com.mysql.cj.jdbc.Driver

  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password:  guest
    listener:
      simple:
        prefetch: 1   #每次只能获取一条消息，处理完才能获取下一条（提升消息处理速度，避免消息堆积）


#  nacos临时实例采用心跳机制（有问题则剔除），非临时实例则nacos主动询问（标记不健康，等待恢复）
# eureka消费者使用pull拉取服务，nacos消费者使用pull+push，若有服务出问题则主动向消费者推送新的列表
  cloud:
    nacos:
      server-addr: localhost:8848      #nacos服务地址
      #配置集群名称，可实现实例的集群属性配置
      #服务间调用默认使用轮训，优先使用相同集群的服务，若不可用，再找其他的
      discovery:
        cluster-name: ServerMaster
#        ephemeral: true    #设置为临时实例
#        namespace: e202b325-d714-407e-9e26-80b28704e370   #填写命名空间id，用于做环境隔离


ribbon:
  eager-load:
    #Ribbon默认采用懒加载，，只有第一次访问时才会去创建LoadBalanceClient，请求时间很长
    #而饥饿加载则会在项目启动时自动创建，降低第一次访问的耗时
    #开启饥饿加载
    enabled: true
    #指定饥饿加载的服务名称
    clients:
      - UserService
      - OrderServicecd
      - ParkingLotService

dubbo:
  consumer:
    check: false    #关闭启动时检查
    retries: 2      #请求服务失败时，重试次数
  application:
    name: AdministratorServiceDubbo        #当前服务名字
    qos-enable: false
#    register-mode: instance   #应用级服务发现
  registry:
    address: nacos://localhost:8848       #注册中心地址
