server:
  port: 9000


spring:

  datasource:
    url: jdbc:mysql://localhost:3306/Smart_parking_data?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "001124"
    driver-class-name: com.mysql.cj.jdbc.Driver

  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password:  guest
    listener:
      simple:
        prefetch: 1   #每次只能获取一条消息，处理完才能获取下一条（提升消息处理速度，避免消息堆积）



#指定日志级别
logging:
  level:
    com.example.administrators: info
  config: classpath:log4j2.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
        #include：refresh ,health ,info #打开部分
        # spring boot 2.x 默认只开启了info 和 health ，*代表开启全部访问
