server:
  port: 9003

spring:

  application:
    name: UserService

  datasource:
    url: jdbc:mysql://localhost:3306/Smart_parking_data?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "001124"
    driver-class-name: com.mysql.cj.jdbc.Driver

    #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password:  guest
    listener:
      simple:
        prefetch: 1   #每次只能获取一条消息，处理完才能获取下一条（提升消息处理速度，避免消息堆积）
    publisher-confirm-type: correlated   #开启publisher-confirm，支持两种类型
                                          #simple同步等待confirm结果，直到超时
                                          #correlated 异步回调，定义一个ConfirmCallBack,MQ返回结果时回调ConfirmCallBack
    publisher-returns: true       #开启publisher-returns，同样是CallBack机制，不过是定义ReturnCallBack
    template:
      mandatory: true         #定义消息路由失败时策略，true则调用ReturnCallBack，false直接丢弃消息

  redis:
    lettuce:
      pool:
        max-active: 8 #最大连接，默认
        max-idle: 8 #最大空闲连接，默认
        min-idle: 0 #最小空闲连接，默认
        max-wait: 100ms #连接等待时间


grpc:
  server:
    port: 9090
    address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
        #include：refresh ,health ,info #打开部分
        # spring boot 2.x 默认只开启了info 和 health ，*代表开启全部访问
dubbo:
  application:
    name: userService
    #当前服务名字
  registry:
    address:
    #注册中心地址
    protocol:
    #注册中心协议
  protocol:
    name: dubbo
    #协议
    port: 100800
