server:
  port: 9001

#spring:
#  jackson:
#    default-property-inclusion: non_null   #Json处理时忽略null


spring:

  application:
    #  服务名称------服务名称不能使用下划线，删除下划线或者使用中划线
    name: OrderService

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1   #每次只能获取一条消息，处理完才能获取下一条（提升消息处理速度，避免消息堆积）
        acknowledge-mode: auto    #设置消息确认机制
        retry:
          enabled: true   #开启消费失败重试
          initial-interval: 1000    #设置失败等待时长为1s
          multiplier: 2   #下次失败的等待时长的倍数
          max-attempts: 3  #最大重试次数  次数耗尽则丢弃
          stateless: true   #true为无状态，false为有，如果业务中包含事务则改为false


  redis:
    lettuce:
      pool:
        max-active: 8 #最大连接，默认
        max-idle: 8 #最大空闲连接，默认
        min-idle: 0 #最小空闲连接，默认
        max-wait: 100ms #连接等待时间




  datasource:
    url: jdbc:mysql://localhost:3306/Smart_parking_order?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "001124"
    driver-class-name: com.mysql.cj.jdbc.Driver


  cloud:
    nacos:
      server-addr: localhost:8848      #nacos服务地址
      #配置集群名称，可实现实例的集群属性配置
      #服务间调用默认使用轮训，优先使用相同集群的服务，若不可用，再找其他的
      discovery:
        cluster-name: ServerMaster
        ephemeral: false    #设置为非临时实例
#        namespace:    #填写命名空间id，用于做环境隔离
    sentinel:   #采用懒加载
      transport:
        dashboard: localhost:8080
        port: 8719
        #这个端口配置会在应用对应的机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互。
        #比如 Sentinel 控制台添加了1个限流规则，会把规则数据 push 给这个 Http Server 接收，Http Server 再将规则注册到 Sentinel 中。
        #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口


ribbon:
  eager-load:
    #Ribbon默认采用懒加载，，只有第一次访问时才会去创建LoadBalanceClient，请求时间很长
    #而饥饿加载则会在项目启动时自动创建，降低第一次访问的耗时
    #开启饥饿加载
    enabled: true
    #指定饥饿加载的服务名称
    clients:
      - UserService
      - ParkingLotService

management:
  endpoints:
    web:
      exposure:
        include: "*"


dubbo:
  consumer:
    check: false    #关闭启动时检查
    retries: 2      #请求服务失败时，重试次数
  application:
    name: OrderServiceDubbo       #当前服务名字
    qos-enable: false   #关闭qos
    enable-file-cache: false
  #    register-mode: instance
  registry:
    address: nacos://localhost:8848       #注册中心地址
  protocol:
    name: tri    #协议
    port: -1      #（ -1 表示自增端口，从 20880 开始）
    host: localhost