server:
  port: 9502

spring:

  application:
    name: gatewayForWeb

  cloud:
    nacos:
      server-addr: localhost:8848      #nacos服务地址
      #配置集群名称，可实现实例的集群属性配置
      #服务间调用默认使用轮训，优先使用相同集群的服务，若不可用，再找其他的
      discovery:
        cluster-name: ServerMaster    #集群名
        ephemeral: false    #设置为非临时实例
    #        namespace:    #填写命名空间id，用于做环境隔离

    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: ForParkingLots     #路由标识，id唯一
          uri: lb://ClientParkingLots    # 路由的目标地址
          predicates:
            - Path=/ParkingLots/**
#          filters:
#            - AddRequestHeader=key,value

        - id: ForAdministrators
          uri: lb://ClientAdministrators    # 路由的目标地址
          predicates:
            - Path=/Administrators/**

      #    filters为路由过滤器  default-filters为全局过滤器  优先级按照声明顺序递增
      #    order值一样时，先执行default-filters，在执行路由过滤器，在执行，GlobalFilter

      globalcors:   #全局跨域处理
        add-to-simple-url-handler-mapping: true     #不拦截CORS的询问请求
        corsConfigurations:
          '[/**]':
            allowedOrigins: #允许哪些网站的跨域请求
              - "http://localhost:8080"
            allowedMethods: # 允许跨域的ajax请求方式
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true  #是否允许携带cookie
            maxAge: 360000    # 这次跨域检测的有效期

  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password:  guest
    listener:
      simple:
        prefetch: 1   #每次只能获取一条消息，处理完才能获取下一条（提升消息处理速度，避免消息堆积）